name: dhmcDeath
main: me.botsko.dhmcdeath.DhmcDeath
version: 0.1.8.2
commands:
   dhmcdeath:
      description: Administrative commands for dhmcDeath.
      usage: /dhmcdeath (reload)
   death:
      description: Return to your place of death
      usage: /death